(defun my-color-theme ()
  "My Color Theme"
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "#000000")
      (background-mode . dark)
      (border-color . "#000000")
      (cursor-color . "#ffffff")
      (foreground-color . "#fdfdfd")
      (mouse-color . "black"))
     (fringe ((t (:background "#000000"))))
     (mode-line ((t (:foreground "#bcbcb3" :background "#2e3e1e"))))
     (region ((t (:background "#28432e"))))
     (font-lock-builtin-face ((t (:foreground "#da9f2f"))))
     (font-lock-comment-face ((t (:foreground "#5186c8"))))
     (font-lock-function-name-face ((t (:foreground "#ffffff"))))
     (font-lock-keyword-face ((t (:foreground "#d76709"))))
     (font-lock-string-face ((t (:foreground "#1ee41b"))))
     (font-lock-type-face ((t (:foreground"#ffffff"))))
     (font-lock-variable-name-face ((t (:foreground "#eeeeec"))))
     (minibuffer-prompt ((t (:foreground "#ce7e03" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'my-color-theme)
